In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
np.array(([1,2],[3,4]))

array([[1, 2],
       [3, 4]])

In [6]:
a=np.array(([1,2],[3,4]))

In [7]:
a[1][1]

4

In [10]:
np.array([1,2,3,4],ndmin=4)

array([[[[1, 2, 3, 4]]]])

In [15]:
np.mat([[1,2,3,4,5],[1,2,4,5,3]])

matrix([[1, 2, 3, 4, 5],
        [1, 2, 4, 5, 3]])

In [16]:
mat1=np.mat([[1,2,3,4,5],[1,2,4,5,3]])

In [17]:
np.asarray(a)

array([[1, 2],
       [3, 4]])

In [18]:
np.asarray(mat1)

array([[1, 2, 3, 4, 5],
       [1, 2, 4, 5, 3]])

In [19]:
np.asanyarray(mat1)

matrix([[1, 2, 3, 4, 5],
        [1, 2, 4, 5, 3]])

In [22]:
np.fromfunction(lambda i,j:i>=j,(4,2))

array([[ True, False],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [25]:
np.mat(np.fromfunction(lambda i,j:i*j+i-j,(3,3),dtype=int))

matrix([[ 0, -1, -2],
        [ 1,  1,  1],
        [ 2,  3,  4]])

In [29]:
np.fromfunction(lambda i,j,z:i*j*z,(9,3,3),dtype=int)

array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  1,  2],
        [ 0,  2,  4]],

       [[ 0,  0,  0],
        [ 0,  2,  4],
        [ 0,  4,  8]],

       [[ 0,  0,  0],
        [ 0,  3,  6],
        [ 0,  6, 12]],

       [[ 0,  0,  0],
        [ 0,  4,  8],
        [ 0,  8, 16]],

       [[ 0,  0,  0],
        [ 0,  5, 10],
        [ 0, 10, 20]],

       [[ 0,  0,  0],
        [ 0,  6, 12],
        [ 0, 12, 24]],

       [[ 0,  0,  0],
        [ 0,  7, 14],
        [ 0, 14, 28]],

       [[ 0,  0,  0],
        [ 0,  8, 16],
        [ 0, 16, 32]]])

In [30]:
np.random.rand(3,3)

array([[0.85483182, 0.65369812, 0.6668927 ],
       [0.55323749, 0.64619807, 0.89987537],
       [0.22617888, 0.06755567, 0.04679127]])

In [39]:
np.random.randint(0,2)

1

In [41]:
a.shape

(2, 2)

In [43]:
a.reshape(1,4)

array([[1, 2, 3, 4]])

In [46]:
a=np.arange(0,24)

In [47]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [48]:
a.reshape(4,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [49]:
a.reshape(6,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [50]:
a.reshape(12,-1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [53]:
list(range(4,10,2))

[4, 6, 8]

In [61]:
np.arange(1,2,.2)

array([1. , 1.2, 1.4, 1.6, 1.8])

In [66]:
arr=np.random.rand(4,5)

In [67]:
arr

array([[0.9694836 , 0.95819646, 0.42544343, 0.96527779, 0.98897204],
       [0.32957355, 0.26965283, 0.29742645, 0.81297863, 0.15736456],
       [0.84066596, 0.23955531, 0.01125355, 0.21840172, 0.86239154],
       [0.90010097, 0.22812577, 0.92987246, 0.94786773, 0.09925032]])

In [64]:
arr[arr>0.5]

array([0.96587676, 0.72552793, 0.51435246, 0.95890743, 0.51653019,
       0.72787031, 0.62001703, 0.57516402, 0.54405823])

In [70]:
arr[[1,2],[2]]

array([0.29742645, 0.01125355])

In [72]:
a= np.array([[1,2],[3,4]])
b=np.array([[5,6,7,8],[9,10,11,12]])

In [73]:
a

array([[1, 2],
       [3, 4]])

In [74]:
b

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [75]:
c=a+b

ValueError: operands could not be broadcast together with shapes (2,2) (2,4) 

In [76]:
d=a*b

ValueError: operands could not be broadcast together with shapes (2,2) (2,4) 

In [77]:
d=a@b

In [78]:
d

array([[23, 26, 29, 32],
       [51, 58, 65, 72]])

In [79]:
d/0

/tmp/ipykernel_155565/2033487706.py:1: RuntimeWarning: divide by zero encountered in true_divide
  d/0


array([[inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [80]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [82]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [83]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [84]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [85]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [86]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [87]:
5+np.ones((3,4))

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [88]:
5+np.zeros((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [89]:
np.empty((2,2))

array([[4.9e-324, 9.9e-324],
       [1.5e-323, 2.0e-323]])

In [91]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [92]:
np.linspace(1,2,10).reshape(5,2)

array([[1.        , 1.11111111],
       [1.22222222, 1.33333333],
       [1.44444444, 1.55555556],
       [1.66666667, 1.77777778],
       [1.88888889, 2.        ]])

In [99]:
np.logspace(2,4,5,base=2.756)

array([ 7.595536  , 12.60950485, 20.93329722, 34.75179537, 57.69216713])

In [103]:
a=np.arange(4,20).reshape(4,4)

In [104]:
a

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [105]:
a.max()

19

In [116]:
 a=np.random.randint(4,40,36).reshape(3,2,6)

In [127]:
a

array([[[26, 32, 27, 21, 12,  8],
        [15, 20, 18, 16, 21, 13]],

       [[13, 39, 11, 21, 31, 24],
        [29, 19,  6, 39, 13, 25]],

       [[32, 18,  7,  8, 25, 15],
        [25, 39, 31, 17,  7, 28]]])

In [128]:
a.max()

39

In [130]:
a.max(axis=1)

array([[26, 32, 27, 21, 21, 13],
       [29, 39, 11, 39, 31, 25],
       [32, 39, 31, 17, 25, 28]])

In [120]:
a.max(axis=0)

array([[32, 39, 27, 21, 31, 24],
       [29, 39, 31, 39, 21, 28]])

In [121]:
 b=np.random.randint(4,40,36).reshape(6,6)

In [122]:
b

array([[38, 34, 18, 17, 25, 35],
       [16, 29, 38,  5, 28, 36],
       [38, 12, 39,  5,  6, 28],
       [ 7, 28,  5, 33, 29, 16],
       [13,  4, 31, 15, 33, 26],
       [37, 36, 37, 10, 29, 34]])

In [123]:
b.max()

39

In [124]:
b.min()

4

In [125]:
b.max(axis=0)

array([38, 36, 39, 33, 33, 36])

In [126]:
b.max(axis=1)

array([38, 38, 39, 33, 33, 37])

In [131]:
a=np.arange(4,40).reshape(6,6)

In [132]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [133]:
a+10

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [134]:
a*2

array([[ 8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40, 42],
       [44, 46, 48, 50, 52, 54],
       [56, 58, 60, 62, 64, 66],
       [68, 70, 72, 74, 76, 78]])

In [135]:
a/0

/tmp/ipykernel_155565/4102073204.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a/0


array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [136]:
a**2

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]])

In [137]:
pow(a,2)

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]])

In [138]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [144]:
b=np.array([[1,1,1,1,1,1],[2,2,2,2,2,2],[2,2,2,2,2,2],[2,2,2,2,2,2],[2,2,2,2,2,2],[2,2,2,2,2,2]])

In [145]:
a+b

array([[ 5,  6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41]])

In [146]:
b=np.array([1,2,3,4,5,6])

In [148]:
b.transpose()

array([1, 2, 3, 4, 5, 6])

In [149]:
b=b.T

array([1, 2, 3, 4, 5, 6])

In [154]:
b=b.reshape(1,-1)

In [155]:
b

array([[1, 2, 3, 4, 5, 6]])

In [156]:
b.T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [157]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [158]:
a+b

array([[ 5,  7,  9, 11, 13, 15],
       [11, 13, 15, 17, 19, 21],
       [17, 19, 21, 23, 25, 27],
       [23, 25, 27, 29, 31, 33],
       [29, 31, 33, 35, 37, 39],
       [35, 37, 39, 41, 43, 45]])

In [159]:
a+b.T

array([[ 5,  6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23, 24],
       [26, 27, 28, 29, 30, 31],
       [33, 34, 35, 36, 37, 38],
       [40, 41, 42, 43, 44, 45]])

In [160]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [161]:
unique_values = np.unique(a)

In [162]:
unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [163]:
unique_values, indices_list = np.unique(a, return_index=True)

In [164]:
unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [165]:
indices_list

array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14])

In [166]:
unique_values, occurrence_count = np.unique(a, return_counts=True)

In [167]:
occurrence_count

array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1])

In [168]:
np.log(a)

array([2.39789527, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.48490665, 2.56494936,
       2.39789527, 2.63905733, 2.89037176, 2.94443898, 2.99573227])

In [169]:
np.log10(a)

array([1.04139269, 1.04139269, 1.07918125, 1.11394335, 1.14612804,
       1.17609126, 1.20411998, 1.23044892, 1.07918125, 1.11394335,
       1.04139269, 1.14612804, 1.25527251, 1.2787536 , 1.30103   ])

In [170]:
x=np.array([1,2,3])

In [171]:
x

array([1, 2, 3])

In [172]:
y=x

In [173]:
y

array([1, 2, 3])

In [174]:
z=np.copy(x)

In [175]:
z

array([1, 2, 3])

In [176]:
x[0]=10

In [177]:
x

array([10,  2,  3])

In [178]:
y

array([10,  2,  3])

In [179]:
z

array([1, 2, 3])

In [180]:
x1=[1,2,3]
y1=x1


In [181]:
y1

[1, 2, 3]

In [182]:
x1[0]=10

In [183]:
y1

[10, 2, 3]

In [184]:
z1=np.copy(x1)

In [185]:
z1

array([10,  2,  3])

In [186]:
x1[0]=1

In [187]:
x1

[1, 2, 3]

In [188]:
y1

[1, 2, 3]

In [189]:
z1

array([10,  2,  3])